config/routes.rb
# Rails.application.routes.draw do
#   map.resources :invites, :controller => 'muck/invites', :collection => { :get_contacts => :post }, :new => { :new => [:get, :post], :compose => [:get, :post] }
# end
Rails.application.routes.draw do
  resources :invites, :controller => 'muck/invites' do
    collection do
      post :get_contacts
      get :compose
    end
  end
end

app/controllers/muck/invites_controller.rb
class Muck::InvitesController < ApplicationController
  unloadable
  before_filter :login_required
  
  def new
    flash.discard
    @page_title = t('muck.invites.new_invites', :app_name => MuckEngine.configuration.application_name)
    respond_to do |format|
      format.html { render :template => 'invites/new', :layout => 'popup' }
      format.pjs { render :template => 'invites/new', :layout => false }
      format.js { render :template => 'invites/new', :layout => false }
    end
  end

  def compose
    flash.discard
    respond_to do |format|
      format.html { render :template => 'invites/compose', :layout => 'popup' }
      format.pjs { render :template => 'invites/compose', :layout => false }
      format.js { render :template => 'invites/compose', :layout => false }
    end
  end
  
  def get_contacts
    @success = true
    begin
      @contacts = User.get_contacts(params[:get_contacts][:email], params[:get_contacts][:password])
      if @contacts.blank?
        @message = t('muck.invites.no_contacts_found')
        @success = false
      end
    rescue Contacts::AuthenticationError => ex
      @success = false
      @message = ex.to_s
    end   
    respond_to do |format|
      format.html do
        flash[:error] = @message if @message
        render :template => 'invites/get_contacts'
      end
      format.json { render :json => { :success => @success, :message => @message, :contacts => @contacts.as_json } }
      format.js do
        @render_contacts_into = params[:render_contacts_into] || 'invite-contacts'
        render :template => 'invites/get_contacts', :layout => false
      end
    end
  end

  def create
    if params[:emails] && !params[:emails].blank?
      emails = params[:emails]
      emails = emails.join(', ') if emails.is_a?(Array)
      current_user.invite(params[:emails], params[:message], current_user)
      @message = t('muck.invites.create_success', :emails => emails, :app_name => MuckEngine.configuration.application_name)
    else
      @message = t('muck.invites.emails_empty')
    end
    respond_to do |format|
      format.html { render :template => 'invites/create', :layout => false }
      format.pjs { render :template => 'invites/create', :layout => false }
      format.js { render :template => 'invites/create', :layout => false }
    end 
    
  rescue ActiveRecord::RecordInvalid => ex
    if @invite
      errors = @invite.errors.full_messages.to_sentence
    else
      errors = ex
    end
    flash[:error] = t('muck.invites.create_error', :errors => errors)
    respond_to do |format|
      format.html { render :template => 'invites/new' }
      format.pjs { render :template => 'invites/new', :layout => false }
      format.js { render :template => 'invites/new', :layout => false }
    end
  end

end

app/helpers/muck_invites_helper.rb
module MuckInvitesHelper

  def contact_list(contacts)
    if MuckInvites.configuration.use_gravatar_in_photo_list
      render :partial => 'invites/contact_list_gravatar', :locals => { :contacts => contacts }
    else
      render :partial => 'invites/contact_list', :locals => { :contacts => contacts }
    end
  end
  
  def invite_ajax_message_container
    output_message_container('invite-messages', 'invite-messages-container')
  end
  
  def invite_ajax_message(message)
    %Q{
    jQuery('#invite-messages-container').show();
    jQuery('#invite-messages').html('#{escape_javascript(message)}');
    }
  end
  
  def contact_container(contacts)
    render :partial => 'invites/contact_container', :locals => { :contacts => contacts }
  end
  
  def google_oauth_for(user)
    user.authentications.find_by_provider('google')
  end
   
  def yahoo_oauth_for(user)
    user.authentications.find_by_provider('yahoo')
  end
 
  # Generates a javascript array of emails from gmail.  Values will be
  # put into a variable named 'gmail_contacts'
  def contacts_for_auto_complete(contacts, ignore_cache = false)
    contacts = contacts.collect{|contact| "'#{contact[:email]}'" }
    "var auto_complete_contacts = [#{contacts.join(',')}];"
  end
  
  def service_contacts(user, ignore_cache = false)
    self.gmail_contacts(user, ignore_cache) + self.yahoo_contacts(user, ignore_cache)
  end
  
  def gmail_contacts(user, ignore_cache = false)
    if @user_gmail_contacts && @user_gmail_contacts[user] && !ignore_cache
      @user_gmail_contacts[user]
    else
      contacts = []
      google = google_oauth_for(user)
      if google
        @user_gmail_contacts ||= {}
        result = google.access_token.get('https://www.google.com/m8/feeds/contacts/default/full?max-results=10000')
        if result.code == '200'
          xml_doc = Nokogiri::XML(result.body) {|config| config.options = Nokogiri::XML::ParseOptions::STRICT }
          contacts = xml_doc.xpath('//xmlns:entry').map do |entry|
            if !entry.xpath('gd:email').blank?
              { :name => entry.xpath('xmlns:title').inner_html,
                :email => entry.xpath('gd:email').attr('address').value }
            end
          end
          contacts.flatten!
        end
        @user_gmail_contacts[user] = contacts
      end
      contacts
    end
  end
  
  def yahoo_contacts(user, ignore_cache = false)
    if @user_yahoo_contacts && @user_yahoo_contacts[user] && !ignore_cache
      @user_yahoo_contacts[user]
    else
      contacts = []
      yahoo = yahoo_oauth_for(user)
      if yahoo
        @user_yahoo_contacts ||= {}
        begin
          result = yahoo.access_token.get("http://social.yahooapis.com/v1/user/#{yahoo.uid}/contacts?format=json&count=max")
        rescue OAuth::Problem => ex
          return contacts
        end
        if result.code == '200'
          json = ActiveSupport::JSON.decode(result.body) 
          contacts = parse_yahoo_contacts(json) 
        end
        @user_yahoo_contacts[user] = contacts
      end
      contacts
    end
  end
  
  
  def parse_yahoo_contacts(json)  
    contacts = []

    return contacts if json['contacts']['contact'].nil?  

    json['contacts']['contact'].each do |contact|   

      name = nil  
      email = nil  

      contact['fields'].each do |field|  
        field['type']  

        if field['type'] == 'name'  
          name = "#{field['value']['givenName']} #{field['value']['familyName']}"  
        end   

        if field['type'] == 'email'  
          email = field['value']  
        end  
      end  

      if(email)  
        name ||= email
        contacts << { :name => name, :email => email}        
      end  
    end  

    contacts  
  end
      
end

app/views/invites/_contact_container.erb
<div class="contact-chooser">
  <div class="contact-chooser-list">
    <fieldset>
      <div class="select-all">
        <input type="checkbox" class="select-all-contacts" />
        <%= t('muck.invites.select_all') %>
      </div>
      <div class="table-wrapper">
        <%= contact_list(contacts) %>
      </div>
    </fieldset>
  </div>
</div>

app/views/invites/_contact_list.erb
<table class="contacts-list">
 <% contacts.each_with_index do |contact,i| %>
   <tr class="contact <%= i%2==0 ? 'even' : 'odd' %>">
     <td class="cb"><input type="checkbox" value="<%= contact[:email] %>" name="emails[]"></td>
     <td class="name"><%= contact[:name] %></td>
     <td class="email"><%= contact[:email] %></td>
   </tr>
 <% end %>
</table>

app/views/invites/_contact_list_gravatar.erb
<% default_image = File.join(root_url, 'images/profile_default.jpg') %>
<table class="contacts-list">
 <% contacts.each_with_index do |contact,i| %>
   <tr class="contact <%= i%2==0 ? 'even' : 'odd' %>">
     <td class="cb"><input type="checkbox" value="<%= contact[:email] %>" name="emails[]"></td>
     <td class="icon"><%= image_tag(gravatar(contact[:email], default_image, 20), :class => 'contact-list-image', :alt => contact[:email]) %></td>
     <td class="name"><%= contact[:name] %></td>
     <td class="email"><%= contact[:email] %></td>
   </tr>
 <% end %>
</table>

app/views/invites/_contacts_from_services.html.erb
<% return unless logged_in? -%>
<% if google_oauth_for(current_user) || yahoo_oauth_for(current_user) -%>
  <p><%=translate('muck.invites.select_emails') %></p>
  <div id="contacts-from-services" class="invite-query">
    <div class="contact-list">
      <%= contact_container(service_contacts(current_user)) %>
    </div>  
  </div>
<% end -%>

app/views/invites/_contacts_loading.erb
<div id="<%=id%>-loading" class="waiting" style="display:none">
  <%= t('muck.invites.retrieving_contacts') %>
</div>

app/views/invites/_contacts_query.erb
<div id="<%=id%>" class="invite-query" style="display:none;">
  <div class="invite-form">
    <p><%=translate('muck.invites.email_password_prompt_title', :title => title) %></p>
    <%= muck_form_for(:get_contacts, :url => get_contacts_invites_path, :html => { :class => 'ajax' } ) do |f| -%>
      <%= f.text_field :email, { :label => t('muck.invites.your_email')} -%>
      <%= f.password_field :password, { :label => t('muck.invites.email_password')} -%>
      <%= hidden_field_tag :render_contacts_into, id %>
      <%= f.submit t('muck.invites.continue_button'), :class => "button invite-submit wait-button" %>
      <%= render :partial => 'invites/contacts_loading', :locals => { :id => id } %>
    <% end -%>
  </div>
  <div class="contacts-privacy">
    <p><%=translate('muck.invites.we_dont_store') %></p>
    <p><%=translate('muck.invites.we_wont_email') %></p>
  </div>
</div>

app/views/invites/_get_contacts.html.erb
<%= output_errors(t('muck.invites.problem_adding_invite'), {:class => 'help-box'}, @invite) %>
<% if !@contacts.blank? -%>
  <% custom_form_for(:invite_contacts, :url => {:action => 'create'}, :html => {:id => "invite-contacts-form", :name => 'invite-contacts-form'} ) do |f| -%>
     <div id="contact-chooser">
       <div id="contact-chooser-list">
         <fieldset>
           <div id="select-all-contacts">
             <input id="select-all" type="checkbox" onclick='jQuery("input[type=checkbox]").attr("checked",jQuery("#select-all:checked").val() != null);' />
             <%= t('muck.invites.select_all') %>
           </div>
           <div class="table-wrapper">
             <table id="contacts-list">
               <% @contacts.each do |contact| %>
                 <tr class="contact">
                   <td class="cb"><input type="checkbox" value="<%= h(contact[1]) %>" name="emails[]"></td>
                   <td class="name"><%= contact[0] %></td>
                   <td class="email"><%= contact[1] %></td>
                 </tr>
               <% end %>
             </table>
           </div>
         </fieldset>
       </div>
     </div>
     <%= f.submit t('muck.invites.invite_button'), :class => "button invite-submit" %>
  <% end -%>
<% end -%>

app/views/invites/_gmail_oauth.erb
<% return unless logged_in? -%>
<div id="gmail" class="invite-query">
  <% if google_oauth_for(current_user) -%>
    <div class="contact-list">
      <%= contact_container(gmail_contacts(current_user)) %>
    </div>    
  <% else -%>
    <p><a href="/auth/google">Connect to Gmail</a></p>
  <% end -%>
</div>

app/views/invites/_invite_scripts.erb
<% content_for :javascript do -%>
<script type="text/javascript" language="JavaScript">
jQuery(document).ready(function() {
  jQuery(".get-contacts-button").click(function() {
    jQuery(this).parent('form').hide();
    jQuery(".contacts-loading").show();
    jQuery("#invite-messages-container").hide();
  });
  apply_ajax_forms();
  
  jQuery('.select-all-contacts').live('click', function(){
    var cbs = jQuery(this).parent('.select-all').siblings('.table-wrapper').find('input:checkbox').attr("checked", jQuery(this).is(':checked'));
    var emails = checked_emails();
    jQuery('#emails').val(emails.join(', '));
  });
  
  jQuery('.contacts-list .cb input[type=checkbox]').live('change', function(){
    var emails = jQuery('#emails').val();
    var email = jQuery(this).val();
    var checked = jQuery(this).is(':checked');
    if(checked){
      jQuery('#emails').val(add_to_list(emails, email));
    } else {
      jQuery('#emails').val(remove_from_list(emails, email));
    }
    included_checkbox_by_email([email], checked);
  });
  
  jQuery('#emails').change(function(){
    set_email_ui();
  });
  
  <%= contacts_for_auto_complete(service_contacts(current_user)) %>
  jQuery("#emails")
  // don't navigate away from the field on tab when selecting an item
  .bind("keydown", function(event){
    if(event.keyCode === $.ui.keyCode.TAB && jQuery(this).data("autocomplete" ).menu.active){
      event.preventDefault();
    }
    set_email_ui();
  })
  .autocomplete({
    minLength: 0,
    source: function( request, response ) {
      // delegate back to autocomplete, but extract the last term
      response( jQuery.ui.autocomplete.filter(
        auto_complete_contacts, extractLast(request.term)));
      },
      focus: function() {
        // prevent value inserted on focus
        return false;
      },
      select: function(event, ui) {
        var terms = split(this.value);
        // remove the current input
        terms.pop();
        // add the selected item
        terms.push(ui.item.value);
        // add placeholder to get the comma-and-space at the end
        terms.push("");
        this.value = terms.join(", ");
        return false;
      }
  });
	
});

function split( val ) {
	return val.split( /,\s*/ );
}
function extractLast( term ) {
	return split( term ).pop();
}

function checked_emails(){
   return get_emails(jQuery('.contacts-list .cb input:checkbox:checked'));
}

function get_emails(cbs){
  return cbs.map(function() {
    return jQuery(this).val();
  }).get();
}

function set_email_ui(){
  var emails = split_list(jQuery('#emails').val());
  excluded_checkbox_by_email(emails, false);
  included_checkbox_by_email(emails, true);
}
// Sets checkboxes that are in 'emails'
function included_checkbox_by_email(emails, checked){
  jQuery('.contacts-list .cb input:checkbox').each(function(index) {
    if(emails.indexOf(jQuery(this).val()) > -1){
      jQuery(this).attr("checked",checked);
    }
  });
}
// Sets checkboxes that aren't in 'emails'
function excluded_checkbox_by_email(emails, checked){
  jQuery('.contacts-list .cb input:checkbox').each(function(index) {
    if(emails.indexOf(jQuery(this).val()) <= -1){
      jQuery(this).attr("checked",checked);
    }
  });
}
</script>
<% end -%>

app/views/invites/_invite_standard.erb
<div id="invite-contacts" class="invite-query">
  <%= invite_ajax_message_container %>
  <div class="invite-form">
    <%= muck_form_for(:get_contacts, :url => get_contacts_invites_path, :html => { :class => 'ajax' } ) do |f| -%>
      <%= f.text_field :email, { :label => t('muck.invites.your_email'),
                                 :tip => t('muck.invites.your_email_help')} -%>
      <%= f.password_field :password, { :label => t('muck.invites.email_password'),
                                        :tip => t('muck.invites.email_password_help')} -%>
      <%= f.submit t('muck.invites.continue_button'), :class => "button invite-submit wait-button" %>
      <%= render :partial => 'invites/contacts_loading' %>
    <% end -%>
  </div>
</div>
<%= render :partial => 'invites/invite_scripts' %>

app/views/invites/_yahoo_oauth.html.erb
<% return unless logged_in? -%>
<div id="yahoo" class="invite-query">
  <% if yahoo_oauth_for(current_user) -%>
    <div class="contact-list">
      <%= contact_container(yahoo_contacts(current_user)) %>
    </div>    
  <% else -%>
    <p><a href="/auth/google">Connect to Yahoo</a></p>
  <% end -%>
</div>

app/views/invites/create.html.erb
<%= @message %>

app/views/invites/get_contacts.html.erb
<%= output_errors(t('muck.invites.problem_adding_invite'), {:class => 'help-box'}, @invite) %>
<% if !@contacts.blank? -%>
  <%= muck_form_for(:invite_contacts, :url => {:action => 'create'}, :html => {:id => "invite-contacts-form", :name => 'invite-contacts-form', :class => 'ajax'} ) do |f| -%>
    <%= contact_container(@contacts) -%>
    <%= f.submit t('muck.invites.invite_button'), :class => "button invite-submit" %>
  <% end -%>
<% end -%>

app/views/invites/new.html.erb
<div id="invite-contacts">
  <h1><%= @page_title %></h1>
  <div id="notice-error" class="error message" style="display:none"></div>
  <div id="get-contacts-form">
    <% custom_form_for(:get_contacts, :url => get_contacts_invites_path,
                                    :html => {:id => "get-contacts-form", :name => 'get-contacts-form',
                                    :class => 'get-contacts-form', :autocomplete => 'off'} ) do |f| -%>
      <%= f.text_field :email, { :label => t('muck.invites.your_email'),
                                 :tip => t('muck.invites.your_email_help')} -%>
      <%= f.password_field :password, { :label => t('muck.invites.email_password'),
                                        :tip => t('muck.invites.email_password_help')} -%>
      <%= f.submit t('muck.invites.continue_button'), :class => "button invite-submit", :id => 'get-contacts-button' %>
    <% end -%>
  </div>
  <div id="contacts-loading" style="display:none">
    <img src="/images/spinner.gif" alt="loading..." />
    <%= t('muck.invites.retrieving_contacts') %>
  </div>
  <div id="contacts-chooser-wrapper" style="display:none;"></div>
</div>

<script type="text/javascript">
jQuery(document).ready(function() {
  jQuery("#get-contacts-button").click(function() {
    jQuery("#get-contacts-form").hide();
    jQuery("#contacts-loading").show();
    jQuery("#notice-error").hide();
    var form = jQuery(this).parents('form');
    jQuery.post(form.attr('action'), form.serialize() + '&format=json',
    function(data){
      var json = eval('(' + data + ')');
      jQuery("#contacts-loading").hide();
      if(!json.success){
        <% if GlobalConfig.growl_enabled -%>
          jQuery.jGrowl.info(json.message);
        <% else -%>
          jQuery("#notice-error").html(json.message);
          jQuery("#notice-error").show();
          jQuery("#get-contacts-form").show();
        <% end -%>
      } else {
        jQuery("#contacts-chooser-wrapper").html(json.html);
        jQuery("#contacts-chooser-wrapper").show();
      }
    });
    return false;
  });
});
</script>